/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:243654e4-38ca-475e-919b-1fb05bac7ce4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SqzYtUdwD",
    "aws_user_pools_web_client_id": "ud3t00sd9pukt2ncgemd0kabp",
    "oauth": {}
};


export default awsmobile;
